"""Tests for source artifact resolution."""

from __future__ import annotations

from pathlib import Path

from intentspec.source_resolve import (
    find_sibling_source,
    is_orphaned,
    parse_source_from_header,
    read_source_text,
    resolve_source_for_intent,
)


def test_find_sibling_agents_md(tmp_path: Path) -> None:
    intent = tmp_path / "intent.yaml"
    agents = tmp_path / "AGENTS.md"
    intent.write_text("version: '1.0'\n", encoding="utf-8")
    agents.write_text("# Agent\n", encoding="utf-8")

    assert find_sibling_source(intent) == agents.resolve()


def test_parse_source_from_header_relative(tmp_path: Path) -> None:
    intent = tmp_path / "intent.yaml"
    agents = tmp_path / "AGENTS.md"
    agents.write_text("# Agent\n", encoding="utf-8")
    intent.write_text(
        "# intent.yaml — generated by intentspec init\n"
        "# Source: AGENTS.md\n"
        "version: '1.0'\n",
        encoding="utf-8",
    )

    assert parse_source_from_header(intent) == agents.resolve()


def test_resolve_prefers_header_over_sibling(tmp_path: Path) -> None:
    intent = tmp_path / "intent.yaml"
    agents = tmp_path / "AGENTS.md"
    skill = tmp_path / "SKILL.md"
    agents.write_text("# Agent\n", encoding="utf-8")
    skill.write_text("---\nname: x\n---\n", encoding="utf-8")
    intent.write_text(
        "# Source: SKILL.md\nversion: '1.0'\n",
        encoding="utf-8",
    )

    assert resolve_source_for_intent(intent) == skill.resolve()


def test_is_orphaned_without_source(tmp_path: Path) -> None:
    intent = tmp_path / "intent.yaml"
    intent.write_text("version: '1.0'\n", encoding="utf-8")
    assert is_orphaned(intent) is True


def test_is_orphaned_with_sibling_source(tmp_path: Path) -> None:
    intent = tmp_path / "intent.yaml"
    (tmp_path / "AGENTS.md").write_text("# Agent\n", encoding="utf-8")
    intent.write_text("version: '1.0'\n", encoding="utf-8")
    assert is_orphaned(intent) is False


def test_resolve_agentskills_directory(tmp_path: Path) -> None:
    skill_dir = tmp_path / "my-skill"
    skill_dir.mkdir()
    (skill_dir / "SKILL.md").write_text("---\nname: x\n---\n", encoding="utf-8")
    intent = tmp_path / "intent.yaml"
    intent.write_text("version: '1.0'\n", encoding="utf-8")

    resolved = resolve_source_for_intent(intent)
    assert resolved == (skill_dir / "SKILL.md").resolve()


def test_read_source_text_returns_content(tmp_path: Path) -> None:
    intent = tmp_path / "intent.yaml"
    agents = tmp_path / "AGENTS.md"
    agents.write_text("# Agent\nUse read_file here.\n", encoding="utf-8")
    intent.write_text("# Source: AGENTS.md\nversion: '1.0'\n", encoding="utf-8")

    assert read_source_text(intent) == "# Agent\nUse read_file here.\n"