"""Emit a ParseResult to YAML / JSON.

`to_intent_yaml(result, source_label)` renders the W1 Intent as an `intent.yaml`
text with a provenance header and per-field `# confidence: ..., source: ...`
comments. The output is byte-deterministic across runs.

`to_full_yaml(result, source_label)` and `to_full_json(result, source_label)`
serialize the entire ParseResult (intent + confidences + sources + warnings +
format) for `--format yaml|json --output -` callers.
"""

from __future__ import annotations

import json
from typing import Any

import yaml

from intentspec.converter.types import FieldSource, ParseResult


_HEADER_TITLE = "# intent.yaml — generated by intentspec init"


def to_intent_yaml(result: ParseResult, source_label: str) -> str:
    """Render the Intent as YAML with provenance header and per-field comments."""
    header = _provenance_header(result, source_label)
    body = _emit_dict(result.intent.to_dict(), result.confidences, result.sources)
    text = "\n".join(header) + "\n\n" + body
    if not text.endswith("\n"):
        text += "\n"
    return text


def to_full_yaml(result: ParseResult, source_label: str) -> str:
    """Serialize the full ParseResult (intent + provenance) as YAML."""
    payload = result.to_serializable()
    payload["source"] = source_label
    return yaml.safe_dump(
        payload,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=10000,
    )


def to_full_json(result: ParseResult, source_label: str) -> str:
    """Serialize the full ParseResult (intent + provenance) as JSON."""
    payload = result.to_serializable()
    payload["source"] = source_label
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def _provenance_header(result: ParseResult, source_label: str) -> list[str]:
    avg = result.average_confidence()
    if avg >= 0.75:
        band = "HIGH"
    elif avg >= 0.40:
        band = "MEDIUM"
    else:
        band = "LOW"
    lines = [
        _HEADER_TITLE,
        f"# Source: {source_label}",
        f"# Format: {result.format}",
        f"# Confidence: {band} ({avg:.2f} average across populated fields)",
    ]
    review = result.low_confidence_keys()
    if review:
        lines.append(f"# Fields requiring review: {', '.join(review)}")
    if result.warnings:
        for w in result.warnings:
            lines.append(f"# Warning: {w}")
    return lines


def _emit_dict(
    data: dict[str, Any],
    confidences: dict[str, float],
    sources: dict[str, FieldSource],
) -> str:
    lines: list[str] = []
    _emit_node_dict(data, "", 0, lines, confidences, sources)
    return "\n".join(lines) + "\n"


def _emit_node_dict(
    data: dict[str, Any],
    path: str,
    indent: int,
    lines: list[str],
    confidences: dict[str, float],
    sources: dict[str, FieldSource],
) -> None:
    pad = " " * indent
    for key, value in data.items():
        child_path = f"{path}.{key}" if path else key
        if isinstance(value, dict):
            if not value:
                comment = _field_comment(child_path, confidences, sources)
                lines.append(f"{pad}{key}: {{}}{comment}")
            else:
                comment = _field_comment(child_path, confidences, sources)
                lines.append(f"{pad}{key}:{comment}")
                _emit_node_dict(value, child_path, indent + 2, lines, confidences, sources)
        elif isinstance(value, list):
            if not value:
                comment = _field_comment(child_path, confidences, sources)
                lines.append(f"{pad}{key}: []{comment}")
            else:
                comment = _field_comment(child_path, confidences, sources)
                lines.append(f"{pad}{key}:{comment}")
                _emit_node_list(value, child_path, indent, lines, confidences, sources)
        else:
            scalar = _yaml_scalar(value)
            comment = _field_comment(child_path, confidences, sources)
            lines.append(f"{pad}{key}: {scalar}{comment}")


def _emit_node_list(
    items: list[Any],
    path: str,
    indent: int,
    lines: list[str],
    confidences: dict[str, float],
    sources: dict[str, FieldSource],
) -> None:
    pad = " " * indent
    for i, item in enumerate(items):
        item_path = f"{path}[{i}]"
        if isinstance(item, dict):
            keys = list(item.keys())
            if not keys:
                lines.append(f"{pad}- {{}}")
                continue
            first_key = keys[0]
            first_value = item[first_key]
            first_path = f"{item_path}.{first_key}"
            inner_pad = " " * (indent + 2)
            if isinstance(first_value, (dict, list)):
                comment = _field_comment(first_path, confidences, sources)
                lines.append(f"{pad}- {first_key}:{comment}")
                if isinstance(first_value, dict):
                    _emit_node_dict(first_value, first_path, indent + 4, lines, confidences, sources)
                else:
                    _emit_node_list(first_value, first_path, indent + 2, lines, confidences, sources)
            else:
                scalar = _yaml_scalar(first_value)
                comment = _field_comment(first_path, confidences, sources)
                lines.append(f"{pad}- {first_key}: {scalar}{comment}")
            for key in keys[1:]:
                value = item[key]
                child_path = f"{item_path}.{key}"
                if isinstance(value, dict):
                    comment = _field_comment(child_path, confidences, sources)
                    if not value:
                        lines.append(f"{inner_pad}{key}: {{}}{comment}")
                    else:
                        lines.append(f"{inner_pad}{key}:{comment}")
                        _emit_node_dict(value, child_path, indent + 4, lines, confidences, sources)
                elif isinstance(value, list):
                    comment = _field_comment(child_path, confidences, sources)
                    if not value:
                        lines.append(f"{inner_pad}{key}: []{comment}")
                    else:
                        lines.append(f"{inner_pad}{key}:{comment}")
                        _emit_node_list(value, child_path, indent + 2, lines, confidences, sources)
                else:
                    scalar = _yaml_scalar(value)
                    comment = _field_comment(child_path, confidences, sources)
                    lines.append(f"{inner_pad}{key}: {scalar}{comment}")
        else:
            scalar = _yaml_scalar(item)
            lines.append(f"{pad}- {scalar}")


def _field_comment(
    path: str,
    confidences: dict[str, float],
    sources: dict[str, FieldSource],
) -> str:
    has_conf = path in confidences
    has_source = path in sources
    if not (has_conf or has_source):
        return ""
    parts: list[str] = []
    if has_conf:
        parts.append(f"confidence: {round(confidences[path], 2):.2f}")
    if has_source:
        parts.append(f"source: {_format_source(sources[path])}")
    return "  # " + ", ".join(parts)


def _format_source(fs: FieldSource) -> str:
    label = fs.extractor or "rule"
    if fs.line is not None:
        label = f"{label} line {fs.line}"
    if fs.snippet:
        snippet = fs.snippet.replace("\n", " ").strip()
        if len(snippet) > 60:
            snippet = snippet[:57] + "..."
        label = f"{label} ({snippet})"
    return label


def _yaml_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    dumped = yaml.safe_dump(
        value,
        default_flow_style=True,
        allow_unicode=True,
        width=10000,
    ).rstrip("\n")
    if dumped.endswith("\n..."):
        dumped = dumped[:-4]
    return dumped
