"""Pre-commit hook installation for IntentSpec."""

from __future__ import annotations

from pathlib import Path

PRE_COMMIT_CONFIG = """# Generated by intentspec init --pre-commit
repos:
  - repo: local
    hooks:
      - id: intentspec
        name: IntentSpec validate/lint/test
        entry: bash -c 'intentspec validate . && intentspec lint . && intentspec test .'
        language: system
        pass_filenames: false
        always_run: true
"""


def install_pre_commit(target_dir: Path) -> Path:
    """Write ``.pre-commit-config.yaml`` in ``target_dir``.

    Args:
        target_dir: Project root where the hook config should be created.

    Returns:
        Path to the written config file.

    Raises:
        FileExistsError: If the config already exists.
    """
    path = target_dir / ".pre-commit-config.yaml"
    if path.exists():
        raise FileExistsError(f"Pre-commit config already exists: {path}")
    path.write_text(PRE_COMMIT_CONFIG, encoding="utf-8")
    return path