"""Shareable agent report card for `intentspec report`.

Produces a compact, social-ready summary of an agent's intent spec:
IDS grade, coverage, lint risks, and key gaps.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from intentspec.coverage import analyze_coverage
from intentspec.lint import lint_intent
from intentspec.models.intent import IntentValidationError
from intentspec.score.ids import compute_ids
from intentspec.source_resolve import read_source_text
from intentspec.spec.validate import validate_file


@dataclass
class ReportCardResult:
    """Shareable report card for a single intent.yaml."""

    agent_name: str
    agent_type: str
    ids_score: float
    grade: str
    coverage_overall: float
    lint_errors: int
    lint_warnings: int
    risks: list[str] = field(default_factory=list)
    highlights: list[str] = field(default_factory=list)
    source_file: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "agent_name": self.agent_name,
            "agent_type": self.agent_type,
            "ids_score": round(self.ids_score, 1),
            "grade": self.grade,
            "coverage_overall": round(self.coverage_overall, 3),
            "lint_errors": self.lint_errors,
            "lint_warnings": self.lint_warnings,
            "risks": self.risks,
            "highlights": self.highlights,
            "source_file": self.source_file,
        }

    def to_markdown(self) -> str:
        lines = [
            f"# Agent Report Card — {self.agent_name}",
            "",
            f"**Grade:** {self.grade} · **IDS:** ~{self.ids_score:.0f}/100 · **Coverage:** {self.coverage_overall:.0%}",
            f"**Type:** {self.agent_type}",
            "",
            "_Generated by [IntentSpec](https://github.com/onicarps/intentspec)_",
            "",
        ]
        if self.highlights:
            lines.append("## Strengths")
            lines.append("")
            for item in self.highlights:
                lines.append(f"- {item}")
            lines.append("")
        if self.risks:
            lines.append("## Risks")
            lines.append("")
            for item in self.risks:
                lines.append(f"- {item}")
            lines.append("")
        lines.append("## Lint Summary")
        lines.append("")
        lines.append(f"- Errors: {self.lint_errors}")
        lines.append(f"- Warnings: {self.lint_warnings}")
        return "\n".join(lines)

    def to_text(self) -> str:
        lines = [
            f"╔══════════════════════════════════════╗",
            f"║  AGENT REPORT CARD                   ║",
            f"╠══════════════════════════════════════╣",
            f"║  {self.agent_name[:34]:<34} ║",
            f"║  Grade: {self.grade:<4}  IDS: ~{self.ids_score:>5.0f}/100       ║",
            f"║  Coverage: {self.coverage_overall:>5.0%}                      ║",
            f"╚══════════════════════════════════════╝",
        ]
        if self.risks:
            lines.append("")
            lines.append("Risks:")
            for risk in self.risks[:5]:
                lines.append(f"  ⚠ {risk}")
        return "\n".join(lines)


def grade_from_score(score: float) -> str:
    if score >= 90:
        return "A"
    if score >= 80:
        return "B"
    if score >= 70:
        return "C"
    if score >= 50:
        return "D"
    return "F"


def generate_report_card(path: Path | str) -> ReportCardResult:
    """Build a shareable report card from an intent.yaml file."""
    path = Path(path)
    intent, errors, _warnings = validate_file(path)
    if errors:
        raise IntentValidationError(errors)

    ids = compute_ids(intent)
    source_text = read_source_text(path)
    coverage = analyze_coverage(intent, source_text=source_text)
    lint = lint_intent(intent, source_text=source_text)

    risks: list[str] = []
    highlights: list[str] = []

    if not intent.non_negotiables:
        risks.append("No non-negotiables declared — hard boundaries missing")
    else:
        hard = [n for n in intent.non_negotiables if n.severity == "hard"]
        if hard:
            highlights.append(f"{len(hard)} hard non-negotiable(s) defined")

    if not intent.tools_denied:
        risks.append("No denied tools — agent has no explicit tool blocklist")
    if intent.tools_allowed:
        highlights.append(f"{len(intent.tools_allowed)} allowed tool(s) with rationale")

    if coverage.overall < 0.7:
        risks.append(f"Low structural coverage ({coverage.overall:.0%}) vs source spec")
    elif coverage.overall >= 0.9:
        highlights.append(f"Strong structural coverage ({coverage.overall:.0%})")

    for issue in lint.errors[:3]:
        risks.append(f"{issue.rule}: {issue.message}")
    for issue in lint.warnings[:2]:
        risks.append(f"{issue.rule}: {issue.message}")

    if ids.score >= 80:
        highlights.append("Well-documented intent spec")

    return ReportCardResult(
        agent_name=intent.agent_name,
        agent_type=intent.agent_type,
        ids_score=ids.score,
        grade=grade_from_score(ids.score),
        coverage_overall=coverage.overall,
        lint_errors=lint.error_count,
        lint_warnings=lint.warning_count,
        risks=risks[:6],
        highlights=highlights[:5],
        source_file=str(path),
    )